### ISSUE TITLE
Is this going to support swagger/OpenAPI spec?

### ISSUE THREAD

**Issue by aeneasr** [GitbookIO/theme-api#13]
All of my API documentation is written in swagger, and I'd like to include that in Gitbook. Is that possible? If not, is it planned?

**Comment by SamyPesse** [comment]
It's planned for the upcoming version: [beta.gitbook.com](https://beta.gitbook.com)

**Comment by aeneasr** [comment]
Hey @SamyPesse - I remember you from the Slate channel :) The beta looks ridiculously awesome, stellar! I'll migrate to that version right away (new docs anyways). You are doing such an amazing job here! I wanted to move from GitBook recently because I wasn't aware how the plugin eco system grew over the past two years. Did a little digging in the docs and was astonished what you added and improved! I am so looking forward to migrate all my docs and have everything in one place.

Full of admiration, keep it going! I hope you are here to stay, because you are really improving the documentation ecosystem.

**Comment by gchokeen** [comment]
Is this feature available now, can i generate api documentation using open api 3 yml file?

**Comment by kdszyubin** [comment]
> Is this feature available now, can i generate api documentation using open api 3 yml file?

cat you generate api doc using openapi 3 yaml file now?

**Comment by FiannaOBrien** [comment]
Does this functionality still exist in the current release?

**Comment by jsmedmar** [comment]
also interested on this

**Comment by jsmedmar** [comment]
ticket should be open as there is no answer on whether one could import an openapi yaml or not

I found this link also: https://gitbook.canny.io/feature-requests/p/import-and-sync-with-swagger-files

**Comment by FiannaOBrien** [comment]
@jsmedmar I have confirmed with Gitbook that this functionality is not available in the current version.

**Comment by ItayKatzCC** [comment]
Any estimations for this feature to be available?

**Comment by cryptiklemur** [comment]
@aeneasr Can you re-open?

**Comment by TrevorHinesley** [comment]
Also needed

**Comment by drasko** [comment]
+1

**Comment by thiamteck** [comment]
+1

**Comment by giezi** [comment]
+1

**Comment by windcbf** [comment]
+1

**Comment by peterzaccha** [comment]
+1

**Comment by gajenc** [comment]
++1

**Comment by NoelOmo** [comment]
+1

**Comment by giomarino** [comment]
+1 any update?

**Comment by mehran-prs** [comment]
+1 
re-open, please!

**Comment by smitchdevelopers** [comment]
+1

**Comment by damv** [comment]
+1

**Comment by LuizGyro** [comment]
+1

**Comment by matthewyuStl** [comment]
+1

**Comment by jo-fr** [comment]
+1

**Comment by idoshilon** [comment]
+1

**Comment by gggina** [comment]
+1

**Comment by meerdaksh** [comment]
+1

**Comment by kogratte** [comment]
Still appreciated :)

**Comment by tomasgomez** [comment]
+1

**Comment by databu** [comment]
+1
