### ISSUE TITLE
Dark theme broken

### ISSUE THREAD

**Issue by nblackburn** [GitbookIO/theme-api#2]
![Preview](http://jmp.sh/yrmjFFW+)

The dark theme looks pretty broken as of now.

**Comment by jpreynat** [comment]
@nblackburn: Which version of gitbook are you using with the theme-api?
Are you running it locally?

**Comment by nblackburn** [comment]
This is hosted on GitHub but the book is private.

**Comment by jpreynat** [comment]
Ok. We updated gitbook.com this morning, can you test it again by regenerating your book?

**Comment by jpreynat** [comment]
Fixed on gitbook.com
