### ISSUE TITLE
Nunjucks includes not working inside {% method %}

### ISSUE THREAD

**Issue by voidmain** [GitbookIO/theme-api#3]
I can't seem to get the `include` tag to work inside a `{% method %}` definition. If I pull the include outside, it works fine. I'm guessing that the plugin is ignoring that or interfering with the templating system somehow.

Here's my example:

```
{% method %}
Some content that renders

{% include "../response-codes.md" %}

This content doesn't render at all.

{% common %}
This content renders in the code example side.

{% endmethod %}
```

**Comment by jpreynat** [comment]
Hi @voidmain,

This issue has been fixed in the plugin with by 0d4a745b1a47de24ddb80bdce6929dd9aba41039.
However, an issue remains on [gitbook](https://github.com/GitbookIO/gitbook) to have nunjucks `include` tag working inside custom tags that we need to fix before this works.
